name: image-ci

# When action should run
# on a new tag push
on:
  push:
    tags:
      - '*'

env:
  image_name: 'pienczyk/yt-2-mp3'

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout self to a runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install QEMU static binaries.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to the Docker Hub. Secrets are configured in the GitHub/repository/settings/secrets/actions
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build, tag and push

      # yt-2-mp3
      # Build metadata for yt-2-mp3 image
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.image_name }}

          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}

      # Build and push yt-2-mp3 to the Docker hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          push: true

      # Scan the image with Trivy vulnerability scanner
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.image_name }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL, HIGH'
